version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=wefriiends-backup 
      - MONGO_INITDB_ROOT_PASSWORD=wefriiends2023
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    container_name: profile-backend
    env_file: .env
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongo-data:
